/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three'
import React, { useEffect, useRef } from 'react'
import { useLoader, useFrame } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useLoader(GLTFLoader, '/bellPeppers.gltf')

  return (
    <group ref={group} {...props} dispose={null}>
      <scene name="AuxScene">
        <group>
          <mesh
            material={materials['Box material 4_0d232f6b-7592-49a6-a67b-5c04ebddef93']}
            geometry={nodes['Box_2_-_baked_16'].geometry}
            name="Box_2_-_baked_16"
          />
          <mesh
            material={materials['Box material 13_6ad06321-2100-4305-a1b4-f218783e9cbf']}
            geometry={nodes['Box_2_-_baked_17'].geometry}
            name="Box_2_-_baked_17"
          />
          <mesh
            material={materials['Box material 9_93373aab-2fbc-40e9-a8da-a73e3f95dc75']}
            geometry={nodes['Box_2_-_baked_18'].geometry}
            name="Box_2_-_baked_18"
          />
          <mesh
            material={materials['Box material 17_8896bdce-fb4b-4abb-b45f-e12c50dae746']}
            geometry={nodes['Box_2_-_baked_19'].geometry}
            name="Box_2_-_baked_19"
          />
          <mesh
            material={materials['Box material 15_7b80fda7-72c4-4bc2-acf7-8ae551b6ff54']}
            geometry={nodes['Box_2_-_baked_20'].geometry}
            name="Box_2_-_baked_20"
          />
          <mesh
            material={materials['Box material 16_5d2bfad7-b7b6-48bf-93db-f086074c8683']}
            geometry={nodes['Box_2_-_baked_21'].geometry}
            name="Box_2_-_baked_21"
          />
          <mesh
            material={materials['Box material 20_1f9c86db-ca61-4474-b456-57030cf33398']}
            geometry={nodes['Box_2_-_baked_22'].geometry}
            name="Box_2_-_baked_22"
          />
          <mesh
            material={materials['Box material 21_cabbe588-04b3-4cfc-a96a-3bd60c497cc7']}
            geometry={nodes['Box_2_-_baked_23'].geometry}
            name="Box_2_-_baked_23"
          />
          <mesh
            material={materials['Box material 18_c7f2d7c1-2da1-4be4-861e-8d6d0a3b68bb']}
            geometry={nodes['Box_2_-_baked_24'].geometry}
            name="Box_2_-_baked_24"
          />
          <mesh
            material={materials['Box material 14_0428f76b-f0b9-4ba9-8e75-1ec1a782958d']}
            geometry={nodes['Box_2_-_baked_25'].geometry}
            name="Box_2_-_baked_25"
          />
          <mesh
            material={materials['Box material 10_c3bf638a-43d8-4ad7-a837-90fc8fb7f1aa']}
            geometry={nodes['Box_2_-_baked_26'].geometry}
            name="Box_2_-_baked_26"
          />
          <mesh
            material={materials['Box material 11_582dfc6e-34ee-4e14-8631-fd719c6b69b1']}
            geometry={nodes['Box_2_-_baked_27'].geometry}
            name="Box_2_-_baked_27"
          />
          <mesh
            material={materials['Box material 12_ca9b5467-517a-4ca2-9890-93459c19eb5a']}
            geometry={nodes['Box_2_-_baked_28'].geometry}
            name="Box_2_-_baked_28"
          />
          <mesh
            material={materials['Box material 2_51241688-a2dd-450b-9c97-c3d81b8471b3']}
            geometry={nodes['Box_2_-_baked_29'].geometry}
            name="Box_2_-_baked_29"
          />
          <mesh
            material={materials['Box material 5_041c3546-4f60-4ba5-9618-8a297d9571dc']}
            geometry={nodes['Box_2_-_baked_30'].geometry}
            name="Box_2_-_baked_30"
          />
          <mesh
            material={materials['Box material 19_2fc334a8-6a2e-4719-811b-afc37da2be69']}
            geometry={nodes['Box_2_-_baked_31'].geometry}
            name="Box_2_-_baked_31"
          />
          <mesh
            material={materials['Box material 22_f6d8054a-bb27-4f57-a0a1-e48b09202fda']}
            geometry={nodes['Box_2_-_baked_32'].geometry}
            name="Box_2_-_baked_32"
          />
          <mesh
            material={materials['Box material 23_e93aec7e-4eff-4cb5-a07d-1d6e881252ed']}
            geometry={nodes['Box_2_-_baked_33'].geometry}
            name="Box_2_-_baked_33"
          />
          <mesh
            material={materials['Box material 24_46bea7f0-bd41-41a0-9633-d5ecfd67be4d']}
            geometry={nodes['Box_2_-_baked_34'].geometry}
            name="Box_2_-_baked_34"
          />
          <mesh
            material={materials['Box material 25_dc064a19-1e71-4ab7-b80d-b673c4a560b1']}
            geometry={nodes['Box_2_-_baked_35'].geometry}
            name="Box_2_-_baked_35"
          />
          <mesh
            material={materials['Box material 26_c567e238-df5e-40d6-b695-a287dcdd2f38']}
            geometry={nodes['Box_2_-_baked_36'].geometry}
            name="Box_2_-_baked_36"
          />
          <mesh
            material={materials['Box material 27_a0c8ea2b-484d-42bb-96b4-999a6c850a57']}
            geometry={nodes['Box_2_-_baked_37'].geometry}
            name="Box_2_-_baked_37"
          />
          <mesh
            material={materials['Box material 28_a8f70e1f-5550-4554-b318-b764057f041b']}
            geometry={nodes['Box_2_-_baked_38'].geometry}
            name="Box_2_-_baked_38"
          />
          <mesh
            material={materials['Box material 29_aeaf9a4f-62e0-4151-9809-1478294f2320']}
            geometry={nodes['Box_2_-_baked_39'].geometry}
            name="Box_2_-_baked_39"
          />
          <mesh
            material={materials['Box material 30_389470fb-ce9c-4df4-9401-44bd6e3e5221']}
            geometry={nodes['Box_2_-_baked_40'].geometry}
            name="Box_2_-_baked_40"
          />
          <mesh
            material={materials['Box material 31_272df3c6-8487-4f05-87c5-c1662d8fcf92']}
            geometry={nodes['Box_2_-_baked_41'].geometry}
            name="Box_2_-_baked_41"
          />
          <mesh
            material={materials['Box material 32_40d95f9d-c20e-49da-9d8f-2eb37cf8d5c7']}
            geometry={nodes['Box_2_-_baked_42'].geometry}
            name="Box_2_-_baked_42"
          />
          <mesh
            material={materials['Box material 3_383691b1-0259-4da9-8089-8adbf2c01a92']}
            geometry={nodes['Box_2_-_baked_43'].geometry}
            name="Box_2_-_baked_43"
          />
          <mesh
            material={materials['Box material 6_10ca403a-5833-42ea-ba2a-51920c126807']}
            geometry={nodes['Box_2_-_baked_44'].geometry}
            name="Box_2_-_baked_44"
          />
          <mesh
            material={materials['Box material 33_99c3fce0-5415-44da-bbac-d63ff12a8ad9']}
            geometry={nodes['Box_2_-_baked_45'].geometry}
            name="Box_2_-_baked_45"
          />
          <mesh
            material={materials['Box material 34_cfba9dc1-d611-4f12-8848-596ada657350']}
            geometry={nodes['Box_2_-_baked_46'].geometry}
            name="Box_2_-_baked_46"
          />
          <mesh
            material={materials['Box material 35_7e0dd382-2b37-47a8-9555-9497424b8f92']}
            geometry={nodes['Box_2_-_baked_47'].geometry}
            name="Box_2_-_baked_47"
          />
          <mesh
            material={materials['Box material 36_dd16d21b-bbd6-4122-a49d-dbb58ee7c3cb']}
            geometry={nodes['Box_2_-_baked_48'].geometry}
            name="Box_2_-_baked_48"
          />
          <mesh
            material={materials['Box material 37_a34dd716-b5b3-4380-ae9f-0c3113d07400']}
            geometry={nodes['Box_2_-_baked_49'].geometry}
            name="Box_2_-_baked_49"
          />
          <mesh
            material={materials['Box material 38_845b7dfc-751a-4763-b975-ab6df020e521']}
            geometry={nodes['Box_2_-_baked_13'].geometry}
            name="Box_2_-_baked_13"
          />
          <mesh
            material={materials['Box material 39_b7663b34-7616-4ad5-a2bb-49302a03a54c']}
            geometry={nodes['Box_2_-_baked_50'].geometry}
            name="Box_2_-_baked_50"
          />
          <mesh
            material={materials['Box material 40_31934a98-e2fe-4022-b836-1fa122130ebf']}
            geometry={nodes['Box_2_-_baked_51'].geometry}
            name="Box_2_-_baked_51"
          />
          <mesh
            material={materials['Box material 41_46563bc1-4d54-462f-8ca4-9e5869382e2b']}
            geometry={nodes['Box_2_-_baked_52'].geometry}
            name="Box_2_-_baked_52"
          />
          <mesh
            material={materials['Box material 42_f67fbdd8-f9ec-4b19-b9a9-687a1335b950']}
            geometry={nodes['Box_2_-_baked_53'].geometry}
            name="Box_2_-_baked_53"
          />
          <mesh
            material={materials['Box material 43_f28901bf-ecfd-4492-b662-16886b568fad']}
            geometry={nodes['Box_2_-_baked_54'].geometry}
            name="Box_2_-_baked_54"
          />
          <mesh
            material={materials['Box material 44_540a968f-6daf-43ff-a4c9-8d52c3d9eb29']}
            geometry={nodes['Box_2_-_baked_55'].geometry}
            name="Box_2_-_baked_55"
          />
          <mesh
            material={materials['Box material 7_8f986c79-23f3-4d0c-81b6-f684a0fda857']}
            geometry={nodes['Box_2_-_baked_56'].geometry}
            name="Box_2_-_baked_56"
          />
          <mesh
            material={materials['Box material 8_a62fc7ea-29e3-4a49-bfa7-2b59334b2ea8']}
            geometry={nodes['Box_2_-_baked_57'].geometry}
            name="Box_2_-_baked_57"
          />
          <mesh
            material={materials['Box material 45_79e0d38a-c969-41f6-abb8-03b58d99ad37']}
            geometry={nodes['Box_2_-_baked_58'].geometry}
            name="Box_2_-_baked_58"
          />
          <mesh
            material={materials['Box material 46_7e5e537c-76b2-4fb0-b4cf-eff6e7bab1b3']}
            geometry={nodes['Box_2_-_baked_59'].geometry}
            name="Box_2_-_baked_59"
          />
          <mesh
            material={materials['Box material 47_5d65435f-1857-40d8-a480-dc83646c4681']}
            geometry={nodes['Box_2_-_baked_60'].geometry}
            name="Box_2_-_baked_60"
          />
          <mesh
            material={materials['Box material 48_b215c485-f2a9-4811-85ed-359c9c8f3e84']}
            geometry={nodes['Box_2_-_baked_61'].geometry}
            name="Box_2_-_baked_61"
          />
          <mesh
            material={materials['Box material 49_1ccb3bf0-3f73-4cda-a86a-8c13b43dc5c0']}
            geometry={nodes['Box_2_-_baked_62'].geometry}
            name="Box_2_-_baked_62"
          />
          <mesh
            material={materials['Box material 50_93fab30e-5b8f-40d1-ba67-176c39a4f94f']}
            geometry={nodes['Box_2_-_baked_63'].geometry}
            name="Box_2_-_baked_63"
          />
          <mesh
            material={materials['Box material 51_0a735a47-68ac-4ef6-847b-63040f9e691c']}
            geometry={nodes['Box_2_-_baked_64'].geometry}
            name="Box_2_-_baked_64"
          />
          <mesh
            material={materials['Box material 52_ba903f33-7d3b-4c0b-8a74-8b59afecb4a9']}
            geometry={nodes['Box_2_-_baked_65'].geometry}
            name="Box_2_-_baked_65"
          />
          <mesh
            material={materials['Box material 53_0eed29b2-0e70-4b97-99c4-3c6a0f251480']}
            geometry={nodes['Box_2_-_baked_66'].geometry}
            name="Box_2_-_baked_66"
          />
          <mesh
            material={materials['Box material 54_ca237ef1-8c55-4313-bf18-86f57a0423e6']}
            geometry={nodes['Box_2_-_baked_67'].geometry}
            name="Box_2_-_baked_67"
          />
          <mesh
            material={materials['Box material 55_bbcd3a7c-b18b-4140-9f59-0a5d82703f44']}
            geometry={nodes['Box_2_-_baked_68'].geometry}
            name="Box_2_-_baked_68"
          />
          <mesh
            material={materials['Box material 56_2ff7f0c3-3004-4322-98c0-e2e84daccc55']}
            geometry={nodes['Box_2_-_baked_69'].geometry}
            name="Box_2_-_baked_69"
          />
          <mesh
            material={materials['Box material 57_a15fb0cc-b82c-479b-b258-fe78971dfb2b']}
            geometry={nodes['Box_2_-_baked_70'].geometry}
            name="Box_2_-_baked_70"
          />
          <mesh
            material={materials['Box material 58_fb7308a3-f1c8-4d0f-a95b-e364a094df0e']}
            geometry={nodes['Box_2_-_baked_71'].geometry}
            name="Box_2_-_baked_71"
          />
          <mesh
            material={materials['Box material 59_29a20f96-df75-4a10-b691-bbff3e7dc62f']}
            geometry={nodes['Box_2_-_baked_72'].geometry}
            name="Box_2_-_baked_72"
          />
          <mesh
            material={materials['Box material 60_99c73be7-eecf-4bee-a7b2-72160ddc17b1']}
            geometry={nodes['Box_2_-_baked_73'].geometry}
            name="Box_2_-_baked_73"
          />
          <mesh
            material={materials['Box material 61_7e96ab0a-737e-4301-aa32-2f27ca5f6e0e']}
            geometry={nodes['Box_2_-_baked_74'].geometry}
            name="Box_2_-_baked_74"
          />
          <mesh
            material={materials['Box material 62_26038a02-fb1e-4ed7-b115-4db58efa5002']}
            geometry={nodes['Box_2_-_baked_75'].geometry}
            name="Box_2_-_baked_75"
          />
          <mesh
            material={materials['Box material 63_7c00eab9-9e13-4f32-976a-a61c9e47f971']}
            geometry={nodes['Box_2_-_baked_76'].geometry}
            name="Box_2_-_baked_76"
          />
          <mesh
            material={materials['Box material 64_f1f96336-da65-4e33-9e16-712b62cc1b5c']}
            geometry={nodes['Box_2_-_baked_77'].geometry}
            name="Box_2_-_baked_77"
          />
          <mesh
            material={materials['Box material 65_262707b8-c874-4743-80c3-3d4a401cdaae']}
            geometry={nodes['Box_2_-_baked_78'].geometry}
            name="Box_2_-_baked_78"
          />
          <mesh
            material={materials['Box material 66_5717b6de-e4c2-4a6d-b6b0-4751d0932848']}
            geometry={nodes['Box_2_-_baked_79'].geometry}
            name="Box_2_-_baked_79"
          />
          <mesh
            material={materials['Box material 67_f5e8c085-73b4-4ec2-86be-e689ebff9a3a']}
            geometry={nodes['Box_2_-_baked_80'].geometry}
            name="Box_2_-_baked_80"
          />
          <mesh
            material={materials['Box material 68_7cb570dc-dc46-4015-bf04-24ca4051567a']}
            geometry={nodes['Box_2_-_baked_81'].geometry}
            name="Box_2_-_baked_81"
          />
          <mesh
            material={materials['Box material 69_cdb89c80-8349-405d-b7e9-2165822b5847']}
            geometry={nodes['Box_2_-_baked_82'].geometry}
            name="Box_2_-_baked_82"
          />
          <mesh
            material={materials['Box material 70_cff8cecf-77d1-4ed4-a4aa-dab4f2a3a378']}
            geometry={nodes['Box_2_-_baked_83'].geometry}
            name="Box_2_-_baked_83"
          />
          <mesh
            material={materials['Box material 71_1284f281-a8a3-4588-9078-ffc76e1d09ba']}
            geometry={nodes['Box_2_-_baked_84'].geometry}
            name="Box_2_-_baked_84"
          />
        </group>
      </scene>
    </group>
  )
}
