/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three'
import React, { useEffect, useRef } from 'react'
import { useLoader, useFrame } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useLoader(GLTFLoader, '/onions.gltf')

  return (
    <group ref={group} {...props} dispose={null}>
      <scene name="AuxScene">
        <group>
          <mesh
            material={
              materials['Box material 1_93920da3-46b4-4b1e-9a0b-4cdf9aa026fa_871af12d-9566-4b68-af54-73076865d432']
            }
            geometry={nodes.main_1.geometry}
            name="main_1"
          />
          <mesh
            material={
              materials['Box material 6_8c085fc6-b1f9-4685-95bb-f89861314608_1c051e88-9f0d-47f6-96c4-d9c2bc0fc916']
            }
            geometry={nodes.das_1.geometry}
            name="das_1"
          />
          <mesh
            material={
              materials['Box material 11_21561d6f-b990-4e59-b836-76a0fb20fae2_392cd052-d8fe-4103-a0a9-fb562a588fd0']
            }
            geometry={nodes.sdaasd_1.geometry}
            name="sdaasd_1"
          />
          <mesh
            material={
              materials['Box material 7_bdf8c63d-5674-46f8-b473-c59552ad0e51_f50c14a5-14d3-4c37-9d8e-675661f801e8']
            }
            geometry={nodes.mid_4_1.geometry}
            name="mid_4_1"
          />
          <mesh
            material={
              materials['Box material 13_bba6e437-b257-46a1-8c39-76b0cde1f910_9a5bc50d-d16c-45b9-b9a4-d3387f6ea572']
            }
            geometry={nodes.mid_5_1.geometry}
            name="mid_5_1"
          />
          <mesh
            material={
              materials['Box material 4_2c64d34e-b375-449a-91ff-dc13003df6b7_1e8784ca-4f38-4e1c-a833-deaf2a492060']
            }
            geometry={nodes.mid_1_1.geometry}
            name="mid_1_1"
          />
          <mesh
            material={
              materials['Box material 12_c293bd87-efcc-477e-8c1a-2eb14b372875_fc21330e-8954-4453-8f02-ad0b87a2c423']
            }
            geometry={nodes.mid_2_1.geometry}
            name="mid_2_1"
          />
          <mesh
            material={
              materials['Box material 5_bd4901aa-6e24-4d1d-8237-a8ec78e41f75_1c8d43d9-4831-4e3c-827b-f0dbb224af5c']
            }
            geometry={nodes.side_1.geometry}
            name="side_1"
          />
          <mesh
            material={
              materials['Box material 2_753e2819-fc5e-49c0-b0d7-32581861b1a0_fc3dfbfd-74bb-48a2-b70c-d6c1b0263f32']
            }
            geometry={nodes.bot_1.geometry}
            name="bot_1"
          />
          <mesh
            material={
              materials['Box material 9_514dea90-c1bf-45f4-a437-dc19a23dc900_cc9697df-9c0e-4f20-a2a5-2c596e18275c']
            }
            geometry={nodes.bot_1_1.geometry}
            name="bot_1_1"
          />
          <mesh
            material={
              materials['Box material 3_05386261-4c16-40e7-8f53-a63a1c9db07b_71525555-f420-4a12-9af3-5e913e23d146']
            }
            geometry={nodes.TOP_1.geometry}
            name="TOP_1"
          />
          <mesh
            material={
              materials['Box material 8_05f1fabc-5dbf-42d7-84f6-087a72559541_65a1137f-8ee3-44eb-9936-da36efe61382']
            }
            geometry={nodes.TOP1_1.geometry}
            name="TOP1_1"
          />
          <mesh
            material={
              materials['Box material 10_bf77a0ce-cefd-4c4c-8863-f7b947e09d09_51ad8007-3cea-467d-aecd-2cec8bf3526d']
            }
            geometry={nodes.side_1_1.geometry}
            name="side_1_1"
          />
          <mesh
            material={
              materials['Box material 14_9fa45020-5a45-49f5-bf89-0d188224ea77_c0a35d4a-9e99-4e4b-a98f-d4f991d1e475']
            }
            geometry={nodes.TOP_2_1.geometry}
            name="TOP_2_1"
          />
          <mesh
            material={
              materials['Box material 16_79977c63-4261-4b2a-aa46-4180a8931f01_d45bbcbb-1962-4e8c-9b09-7ced74543bc0']
            }
            geometry={nodes.TOP_4_1.geometry}
            name="TOP_4_1"
          />
          <mesh
            material={
              materials['Box material 15_723502af-ede7-4c12-b8bc-82283aa02aed_252833dc-9b19-49ab-984a-dd7b05281e8a']
            }
            geometry={nodes.TOP_3_1.geometry}
            name="TOP_3_1"
          />
          <mesh
            material={
              materials['Box material 49_83376ded-fa38-47f6-9e17-ba3eaa6eee59_a5f934f4-b120-4a5c-afad-e07f5aed3660']
            }
            geometry={nodes.main_4.geometry}
            name="main_4"
          />
          <mesh
            material={
              materials['Box material 50_370b0ddf-df43-497a-ab93-a94d039675a2_c1de7ef0-60bf-40c2-accc-5ffeb69bdbbe']
            }
            geometry={nodes.das_4.geometry}
            name="das_4"
          />
          <mesh
            material={
              materials['Box material 51_77a4a225-f6f2-4fbb-a2f4-06902fa48033_667345d5-f97f-4e52-930b-18f132a4b1b4']
            }
            geometry={nodes.sdaasd_4.geometry}
            name="sdaasd_4"
          />
          <mesh
            material={
              materials['Box material 52_022a562d-7e93-4df8-9076-c782c11f3dc5_ec320263-177d-493b-bdcc-bde1e3fbfe45']
            }
            geometry={nodes.mid_4_4.geometry}
            name="mid_4_4"
          />
          <mesh
            material={
              materials['Box material 53_26ef71de-8ba5-43ee-8762-e885293a653c_e43c9c3e-4e44-4d1f-a88e-ac3d192a01c5']
            }
            geometry={nodes.mid_5_4.geometry}
            name="mid_5_4"
          />
          <mesh
            material={
              materials['Box material 54_b8c08111-38eb-426e-8344-99fa130e6040_6fe69ea9-377e-4ec8-9cb2-8ad17a140124']
            }
            geometry={nodes.mid_1_4.geometry}
            name="mid_1_4"
          />
          <mesh
            material={
              materials['Box material 55_9c663e04-2432-4a1d-ad87-9bb992b2e952_bec45b46-a56e-4eb5-92e4-315150196262']
            }
            geometry={nodes.mid_2_4.geometry}
            name="mid_2_4"
          />
          <mesh
            material={
              materials['Box material 56_625f00de-b8dc-4e17-a03e-4e91ddaf0a28_8383ad75-e3cc-4b35-91d9-1ab00f0d3e0e']
            }
            geometry={nodes.side_4.geometry}
            name="side_4"
          />
          <mesh
            material={
              materials['Box material 57_edf0ffa4-7743-4449-bf8b-43f1f35a9b8d_7d7b39d3-eef8-457c-972d-e86398cfd778']
            }
            geometry={nodes.bot_4.geometry}
            name="bot_4"
          />
          <mesh
            material={
              materials['Box material 58_c8c16aca-5c31-4f07-a7e3-047fdbeffde0_eb13cfb3-24df-4e33-925c-f532a977bfc0']
            }
            geometry={nodes.bot_1_4.geometry}
            name="bot_1_4"
          />
          <mesh
            material={
              materials['Box material 59_739a58e1-5bd2-406f-a183-d6ab5ae0d750_17bebc41-4282-4a9b-a4e2-ddc10cfb8d9e']
            }
            geometry={nodes.TOP_4.geometry}
            name="TOP_4"
          />
          <mesh
            material={
              materials['Box material 61_67226cae-b34b-4526-bd9a-a5903f1649a2_0c57cff2-8845-4159-b813-9bb2af64b4e2']
            }
            geometry={nodes.side_1_4.geometry}
            name="side_1_4"
          />
          <mesh
            material={
              materials['Box material 62_eeec26e5-97b2-4583-a15f-c4c5eddebb26_2f32a95f-b977-4316-bbe0-7912d5ddef45']
            }
            geometry={nodes.TOP_2_4.geometry}
            name="TOP_2_4"
          />
          <mesh
            material={
              materials['Box material 63_e6c06988-fa21-46b9-9315-502c58459f52_868f3bcc-2fcc-467a-89c6-6e87f1baed7b']
            }
            geometry={nodes.TOP_3_4.geometry}
            name="TOP_3_4"
          />
          <mesh
            material={
              materials['Box material 64_fa447a5d-274f-4679-b51d-d0eaef9de0de_50aff027-bd95-48a5-96a5-a82a992ef3a4']
            }
            geometry={nodes.TOP_4_4.geometry}
            name="TOP_4_4"
          />
          <mesh
            material={
              materials['Box material 60_ed7ad6ad-3ff7-4c02-8731-da8e332d0137_f8168398-e82b-4c04-bcda-d4be2ef0fe40']
            }
            geometry={nodes.TOP1_4.geometry}
            name="TOP1_4"
          />
          <mesh
            material={
              materials['Box material 65_20252af2-3649-40b6-b3bc-172141c0f281_b7c58d75-8255-4916-8184-5a3a3da84b34']
            }
            geometry={nodes.main.geometry}
            name="main"
          />
          <mesh
            material={
              materials['Box material 66_0a61c7bf-1d34-4b39-8330-c4e848f93a66_5b715861-a7c1-408c-a9b0-14608d70e83f']
            }
            geometry={nodes.das.geometry}
            name="das"
          />
          <mesh
            material={
              materials['Box material 67_e88dff74-ef79-4924-a60d-43e555de9c9f_a433d71e-584e-474f-8379-8d9944b48f40']
            }
            geometry={nodes.sdaasd.geometry}
            name="sdaasd"
          />
          <mesh
            material={
              materials['Box material 68_21efdd23-321e-41e5-a5f9-fb400f8af19c_c4ac9851-3a23-49a0-a9f6-c6cb361ac378']
            }
            geometry={nodes.mid_4.geometry}
            name="mid_4"
          />
          <mesh
            material={
              materials['Box material 69_6314f73d-87dc-42a3-bec9-1ccb30bbb80b_b38933ab-dd0f-4b93-9fb2-518d00718c48']
            }
            geometry={nodes.mid_5.geometry}
            name="mid_5"
          />
          <mesh
            material={
              materials['Box material 70_3b26d331-46b1-4dab-af58-ed353602ea3b_0f028504-5234-436e-be8e-168190732461']
            }
            geometry={nodes.mid_1.geometry}
            name="mid_1"
          />
          <mesh
            material={
              materials['Box material 71_bb8d59ef-0ee1-4922-b255-916ca94abca8_c3a8ba30-bcc0-4530-bf3f-aff12677bdda']
            }
            geometry={nodes.mid_2.geometry}
            name="mid_2"
          />
          <mesh
            material={
              materials['Box material 72_c5c45d79-7690-4f21-aeeb-40d8376f237e_cab01db1-02f2-4d0a-adb2-4d0cdee706ce']
            }
            geometry={nodes.side.geometry}
            name="side"
          />
          <mesh
            material={
              materials['Box material 73_471a2002-e894-46bb-91ac-9b2107833f21_bd5ad265-9cc5-429f-8b4a-3a1dcd9e5040']
            }
            geometry={nodes.bot.geometry}
            name="bot"
          />
          <mesh
            material={
              materials['Box material 74_23a28d4a-728e-4956-bae9-ea38d5715308_135c1922-b5e4-454f-82ea-609ac15a5fd4']
            }
            geometry={nodes.bot_1.geometry}
            name="bot_1"
          />
          <mesh
            material={
              materials['Box material 75_bc572455-0af9-4173-b761-8e6d854d11b9_06c6a805-732b-4363-a507-1c0e7f8e62a4']
            }
            geometry={nodes.TOP.geometry}
            name="TOP"
          />
          <mesh
            material={
              materials['Box material 77_c0528201-863c-410e-9b8d-942b06c934b2_7b4c548f-9dfd-429a-8303-30bf04aab299']
            }
            geometry={nodes.side_1.geometry}
            name="side_1"
          />
          <mesh
            material={
              materials['Box material 78_64cc1371-c7f8-48cc-ac87-9e2ee9c63a25_1fbb8be5-bb1c-4cfc-b5d7-8f77d0f1d879']
            }
            geometry={nodes.TOP_2.geometry}
            name="TOP_2"
          />
          <mesh
            material={
              materials['Box material 79_e7fd5607-6c1c-4209-9cf0-3105c496c164_6700f2e1-dc7e-4559-8892-528b98b1532c']
            }
            geometry={nodes.TOP_3.geometry}
            name="TOP_3"
          />
          <mesh
            material={
              materials['Box material 80_17253769-4f74-468d-9257-f646d8698d33_5c0cb042-57b2-46ce-a596-dac4bf480335']
            }
            geometry={nodes.TOP_4.geometry}
            name="TOP_4"
          />
          <mesh
            material={
              materials['Box material 76_df2fb5e7-3e93-458a-9ce7-1f3379a74be0_b1ad3f53-c6ce-4947-a5fc-d94fdfc763c6']
            }
            geometry={nodes.TOP1.geometry}
            name="TOP1"
          />
        </group>
      </scene>
    </group>
  )
}
