/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three'
import React, { useEffect, useRef } from 'react'
import { useLoader, useFrame } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useLoader(GLTFLoader, '/potatoes.gltf')

  return (
    <group ref={group} {...props} dispose={null}>
      <scene name="AuxScene">
        <group>
          <mesh
            material={materials['Box material 1_93920da3-46b4-4b1e-9a0b-4cdf9aa026fa']}
            geometry={nodes.main.geometry}
            name="main"
          />
          <mesh
            material={materials['Box material 6_8c085fc6-b1f9-4685-95bb-f89861314608']}
            geometry={nodes.das.geometry}
            name="das"
          />
          <mesh
            material={materials['Box material 11_21561d6f-b990-4e59-b836-76a0fb20fae2']}
            geometry={nodes.sdaasd.geometry}
            name="sdaasd"
          />
          <mesh
            material={materials['Box material 7_bdf8c63d-5674-46f8-b473-c59552ad0e51']}
            geometry={nodes.mid_4.geometry}
            name="mid_4"
          />
          <mesh
            material={materials['Box material 13_bba6e437-b257-46a1-8c39-76b0cde1f910']}
            geometry={nodes.mid_5.geometry}
            name="mid_5"
          />
          <mesh
            material={materials['Box material 4_2c64d34e-b375-449a-91ff-dc13003df6b7']}
            geometry={nodes.mid_1.geometry}
            name="mid_1"
          />
          <mesh
            material={materials['Box material 12_c293bd87-efcc-477e-8c1a-2eb14b372875']}
            geometry={nodes.mid_2.geometry}
            name="mid_2"
          />
          <mesh
            material={materials['Box material 5_bd4901aa-6e24-4d1d-8237-a8ec78e41f75']}
            geometry={nodes.side.geometry}
            name="side"
          />
          <mesh
            material={materials['Box material 2_753e2819-fc5e-49c0-b0d7-32581861b1a0']}
            geometry={nodes.bot.geometry}
            name="bot"
          />
          <mesh
            material={materials['Box material 3_05386261-4c16-40e7-8f53-a63a1c9db07b']}
            geometry={nodes.TOP.geometry}
            name="TOP"
          />
          <mesh
            material={materials['Box material 9_514dea90-c1bf-45f4-a437-dc19a23dc900']}
            geometry={nodes.bot_1.geometry}
            name="bot_1"
          />
          <mesh
            material={materials['Box material 8_05f1fabc-5dbf-42d7-84f6-087a72559541']}
            geometry={nodes.TOP1.geometry}
            name="TOP1"
          />
          <mesh
            material={materials['Box material 10_bf77a0ce-cefd-4c4c-8863-f7b947e09d09']}
            geometry={nodes.side_1.geometry}
            name="side_1"
          />
          <mesh
            material={materials['Box material 14_12bdbddc-bec5-4e6e-9ba2-e213000db4b1']}
            geometry={nodes.main_1.geometry}
            name="main_1"
          />
          <mesh
            material={materials['Box material 15_2c20d402-fe5d-49d3-8a66-47241f375de3']}
            geometry={nodes.das_1.geometry}
            name="das_1"
          />
          <mesh
            material={materials['Box material 16_34818e31-780a-4fc5-80bd-7cb173d0c4b3']}
            geometry={nodes.sdaasd_1.geometry}
            name="sdaasd_1"
          />
          <mesh
            material={materials['Box material 17_126920f0-1499-4290-9e90-68baf0c4ce27']}
            geometry={nodes.mid_6.geometry}
            name="mid_6"
          />
          <mesh
            material={materials['Box material 19_e100380d-0ba9-465a-8608-73b03a1d5c5e']}
            geometry={nodes.mid_3.geometry}
            name="mid_3"
          />
          <mesh
            material={materials['Box material 20_1ac0c2a5-f462-4ade-9505-c83fbcac8b6f']}
            geometry={nodes.mid_8.geometry}
            name="mid_8"
          />
          <mesh
            material={materials['Box material 21_fa0b273f-3902-4454-ba9a-33e55c0141fc']}
            geometry={nodes.side_2.geometry}
            name="side_2"
          />
          <mesh
            material={materials['Box material 22_29e9d4a8-5aa6-4ffc-ada6-53654565cbde']}
            geometry={nodes.bot_2.geometry}
            name="bot_2"
          />
          <mesh
            material={materials['Box material 23_aedf8c05-8a64-496a-9275-0db132a3e819']}
            geometry={nodes.TOP_1.geometry}
            name="TOP_1"
          />
          <mesh
            material={materials['Box material 24_2ab6cb19-72bb-4b7e-b15e-c417f7ec6315']}
            geometry={nodes.bot_3.geometry}
            name="bot_3"
          />
          <mesh
            material={materials['Box material 25_84ade99d-a223-4ba5-b70e-bd7d83e009e8']}
            geometry={nodes.TOP1_1.geometry}
            name="TOP1_1"
          />
          <mesh
            material={materials['Box material 26_cfe603a8-a855-4ce3-b2a9-a27d87bc7f55']}
            geometry={nodes.side_3.geometry}
            name="side_3"
          />
          <mesh
            material={materials['Box material 18_073f73e6-a8c2-46b9-a5f3-458062f8d385']}
            geometry={nodes.mid_7.geometry}
            name="mid_7"
          />
        </group>
      </scene>
    </group>
  )
}
